<?php

namespace App\Entity;

use App\Repository\CourseSummaryRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CourseSummaryRepository::class)]
class CourseSummary
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'courseSummaries')]
    #[ORM\JoinColumn(nullable: false, onDelete: "CASCADE")]
    private ?Cours $cours = null;

    #[ORM\Column(type: 'text')]
    private ?string $summaryText = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $generatedAt = null;

    #[ORM\Column(type: 'boolean', options: ['default' => true])]
    private ?bool $isAutoGenerated = true;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $summaryType = 'standard';

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $keywords = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCours(): ?Cours
    {
        return $this->cours;
    }

    public function setCours(?Cours $cours): static
    {
        $this->cours = $cours;
        return $this;
    }

    public function getSummaryText(): ?string
    {
        return $this->summaryText;
    }

    public function setSummaryText(string $summaryText): static
    {
        $this->summaryText = $summaryText;
        return $this;
    }

    public function getGeneratedAt(): ?\DateTimeInterface
    {
        return $this->generatedAt;
    }

    public function setGeneratedAt(\DateTimeInterface $generatedAt): static
    {
        $this->generatedAt = $generatedAt;
        return $this;
    }

    public function isAutoGenerated(): ?bool
    {
        return $this->isAutoGenerated;
    }

    public function setIsAutoGenerated(bool $isAutoGenerated): static
    {
        $this->isAutoGenerated = $isAutoGenerated;
        return $this;
    }

    public function getSummaryType(): ?string
    {
        return $this->summaryType;
    }

    public function setSummaryType(?string $summaryType): static
    {
        $this->summaryType = $summaryType;
        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): static
    {
        $this->keywords = $keywords;
        return $this;
    }
}