<?php

namespace App\Controller;

use App\Entity\CourseSummary;
use App\Entity\Cours;
use App\Repository\CoursRepository;
use App\Repository\CourseSummaryRepository;
use App\Repository\RessourcePedagogiqueRepository;
use App\Service\AISummaryService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/summary')]
class SummaryController extends AbstractController
{
    private EntityManagerInterface $entityManager;
    private AISummaryService $aiSummaryService;
    private CourseSummaryRepository $summaryRepository;
    private RessourcePedagogiqueRepository $ressourceRepository;

    public function __construct(
        EntityManagerInterface $entityManager,
        AISummaryService $aiSummaryService,
        CourseSummaryRepository $summaryRepository,
        RessourcePedagogiqueRepository $ressourceRepository
    ) {
        $this->entityManager       = $entityManager;
        $this->aiSummaryService    = $aiSummaryService;
        $this->summaryRepository   = $summaryRepository;
        $this->ressourceRepository = $ressourceRepository;
    }

    #[Route('/generate/{id}', name: 'summary_generate', methods: ['GET', 'POST'])]
    public function generateSummary(int $id, CoursRepository $coursRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $cours = $coursRepository->find($id);

        if (!$cours || $cours->getStatut() !== 'publié') {
            throw $this->createNotFoundException('Cours non trouvé');
        }

        $ressources = $this->ressourceRepository->findBy(['cours' => $cours]);

        try {
            $type   = $this->isGranted('ROLE_ADMIN') ? 'ai' : 'standard';
            $result = $this->aiSummaryService->generateSummary($cours, $ressources, $type);

            $summary = new CourseSummary();
            $summary->setCours($cours);
            $summary->setSummaryText($result['summary']);
            $summary->setGeneratedAt(new \DateTime());
            $summary->setIsAutoGenerated(true);
            $summary->setSummaryType($type);
            $summary->setKeywords($result['keywords'] ?? '');

            $this->entityManager->persist($summary);
            $this->entityManager->flush();

            $this->addFlash('success', 'Résumé généré avec succès !');
            return $this->redirectToRoute('summary_view', ['id' => $cours->getId()]);

        } catch (\Exception $e) {
            $this->addFlash('error', 'Erreur lors de la génération du résumé : ' . $e->getMessage());
            return $this->redirectToRoute('course_show', ['id' => $cours->getId()]);
        }
    }

    #[Route('/view/{id}', name: 'summary_view', methods: ['GET'])]
    public function viewSummary(int $id, CoursRepository $coursRepository): Response
    {
        $cours = $coursRepository->find($id);

        if (!$cours || $cours->getStatut() !== 'publié') {
            throw $this->createNotFoundException('Cours non trouvé');
        }

        $latestSummary = $this->summaryRepository->findLatestByCourse($cours);

        return $this->render('summary/view.html.twig', [
            'course'     => $cours,
            'summary'    => $latestSummary,
            'ressources' => $this->ressourceRepository->findBy(['cours' => $cours])
        ]);
    }

    #[Route('/export/{id}', name: 'summary_export_pdf', methods: ['GET'])]
    public function exportSummaryPdf(int $id, CoursRepository $coursRepository): Response
    {
        $cours = $coursRepository->find($id);

        if (!$cours || $cours->getStatut() !== 'publié') {
            throw $this->createNotFoundException('Cours non trouvé');
        }

        $summary    = $this->summaryRepository->findLatestByCourse($cours);
        $ressources = $this->ressourceRepository->findBy(['cours' => $cours]);

        if (!$summary) {
            $result = $this->aiSummaryService->generateSummary($cours, $ressources, 'standard');

            $summary = new CourseSummary();
            $summary->setCours($cours);
            $summary->setSummaryText($result['summary']);
            $summary->setGeneratedAt(new \DateTime());
            $summary->setIsAutoGenerated(true);
            $summary->setSummaryType('standard');
            $summary->setKeywords($result['keywords'] ?? '');

            $this->entityManager->persist($summary);
            $this->entityManager->flush();
        }

        $pdfOptions = new \Dompdf\Options();
        $pdfOptions->set('defaultFont', 'Arial');
        $pdfOptions->set('isRemoteEnabled', true);
        $pdfOptions->set('isHtml5ParserEnabled', true);

        $dompdf = new \Dompdf\Dompdf($pdfOptions);

        $html = $this->renderView('summary/export_pdf.html.twig', [
            'course'      => $cours,
            'summary'     => $summary,
            'ressources'  => $ressources,
            'date_export' => new \DateTime()
        ]);

        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        $fileName = sprintf('resume-cours-%s-%s.pdf', $cours->getId(), date('Y-m-d'));

        return new Response(
            $dompdf->output(),
            Response::HTTP_OK,
            [
                'Content-Type'        => 'application/pdf',
                'Content-Disposition' => 'inline; filename="' . $fileName . '"'
            ]
        );
    }

    #[Route('/history/{id}', name: 'summary_history', methods: ['GET'])]
    public function summaryHistory(int $id, CoursRepository $coursRepository): JsonResponse
    {
        $cours = $coursRepository->find($id);

        if (!$cours) {
            return $this->json(['error' => 'Cours non trouvé'], 404);
        }

        $summaries = $this->summaryRepository->findBy(
            ['cours' => $cours],
            ['generatedAt' => 'DESC'],
            10
        );

        $data = [];
        foreach ($summaries as $s) {
            $data[] = [
                'id'           => $s->getId(),
                'summary'      => substr($s->getSummaryText(), 0, 200) . '...',
                'generated_at' => $s->getGeneratedAt()->format('d/m/Y H:i'),
                'type'         => $s->getSummaryType(),
                'keywords'     => $s->getKeywords()
            ];
        }

        return $this->json(['success' => true, 'summaries' => $data]);
    }

    #[Route('/delete-old', name: 'summary_delete_old', methods: ['POST'])]
    public function deleteOldSummaries(Request $request): JsonResponse
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $days    = $request->get('days', 30);
        $deleted = $this->summaryRepository->deleteOldSummaries($days);

        return $this->json([
            'success' => true,
            'message' => "{$deleted} anciens résumés supprimés"
        ]);
    }
}